"""Tests for BriefingSnapshotWriter (Angle 1') — deterministic snapshot.md.

Hard rules per CLAUDE.md and .claude/rules/improvement.md:
- NO mocks. Real classes against real disk via tmp_path.
- briefing.md is NEVER touched. We assert that explicitly.
- Atomic-write semantics: failures must NOT leave partial files; heartbeat
  records the failure.
"""
from __future__ import annotations

import json
import logging
import os
import time
from pathlib import Path

import pytest

from src.scanner.automation.briefing_snapshot import BriefingSnapshotWriter


# ── Helpers ──────────────────────────────────────────────────────────

def _write_json(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload), encoding="utf-8")


def _seed_minimal_state(root: Path, halted: bool = False) -> None:
    """Drop a minimal viable .claude/state.json + heartbeat.json under root."""
    _write_json(root / ".claude" / "state.json", {
        "halted": halted,
        "mode": "demo",
        "scan_cycle_count": 42,
        "safe_restart": {"at": "2026-05-09T15:17:50Z", "reason": "operator_ctrl_r"},
    })
    _write_json(root / ".claude" / "heartbeat.json", {
        "pid": 12345,
        "ts_iso": "2026-05-10T18:57:33+00:00",
        "scanner_alive": True,
        "cycle_count": 42,
    })
    _write_json(root / ".claude" / "alert_state.json", {
        "active_alerts": [],
        "last_fired": {"consecutive_losses": 1778332923.0},
        "last_updated": "2026-05-10T18:57:02",
    })


# ── Tests ────────────────────────────────────────────────────────────

def test_writer_produces_snapshot_with_all_sections(tmp_path: Path) -> None:
    """All 8 template sections render when source files are present."""
    _seed_minimal_state(tmp_path, halted=False)
    # Seed a ChangePackage so that section is non-empty.
    _write_json(tmp_path / ".claude" / "meta" / "changes" / "abc123.json", {
        "change_id": "abc123",
        "stage": "deployed_shadow",
        "incident": {"kind": "auto_halt_loss_streak"},
        "updated_at": "2026-05-10T15:00:00+00:00",
        "created_at": "2026-05-10T14:00:00+00:00",
    })
    # Seed a recent closed trade
    _write_json(tmp_path / "trained_data" / "trade_journal_rl.json", [{
        "trade_id": "live_1",
        "pair": "EUR_USD",
        "direction": "LONG",
        "outcome": "WIN",
        "pnl_pips": 12.4,
        "confidence": 0.71,
        "exit_reason": "tp_hit",
        # Use a "now-ish" close time inside the 24h window
        "close_time": _now_iso(),
    }])
    # Virtual trades line counter
    vt_path = tmp_path / "trained_data" / "virtual_trades.jsonl"
    vt_path.parent.mkdir(parents=True, exist_ok=True)
    vt_path.write_text("\n".join(['{"a":1}'] * 7) + "\n")

    writer = BriefingSnapshotWriter(project_root=tmp_path)
    assert writer.write_now(trigger="boot") is True

    snap = (tmp_path / ".claude" / "brain" / "snapshot.md").read_text()

    # Section 1: Header
    assert "# Buddy Snapshot —" in snap
    assert "HEAD:" in snap
    assert "halted:" in snap
    assert "last-write-trigger:" in snap
    # Section 2: Halt context (running branch)
    assert "## Halt context" in snap
    assert "running (mode=" in snap
    # Section 3: Recent trade outcomes
    assert "## Recent trade outcomes (24h)" in snap
    assert "EUR_USD" in snap
    assert "LONG" in snap
    # Section 4: Active alerts
    assert "## Active alerts" in snap
    # Section 5: Recent ChangePackages
    assert "## Recent ChangePackages" in snap
    assert "abc123" in snap
    assert "auto_halt_loss_streak" in snap
    # Section 6: Model freshness
    assert "## Model freshness" in snap
    # Section 7: Scan stats
    assert "## Scan stats" in snap
    assert "virtual_trades.jsonl lines" in snap
    assert "`7`" in snap  # 7 virtual trades lines
    # Section 8: Footer
    assert "generated by BriefingSnapshotWriter" in snap
    assert "briefing.md is human-owned" in snap


def test_missing_source_files_dont_crash(tmp_path: Path) -> None:
    """An empty tmp dir still produces a snapshot with placeholders."""
    writer = BriefingSnapshotWriter(project_root=tmp_path)
    assert writer.write_now(trigger="boot") is True

    snap_path = tmp_path / ".claude" / "brain" / "snapshot.md"
    assert snap_path.exists()
    snap = snap_path.read_text()

    # Halted should default to False -> running branch
    assert "running (mode=" in snap
    # No closed trades placeholder
    assert "no closed trades in last 24h" in snap
    # No ChangePackages placeholder
    assert "no ChangePackages on disk" in snap
    # Footer always present
    assert "generated by BriefingSnapshotWriter" in snap


def test_corrupt_json_source_logged_not_crashed(tmp_path: Path, caplog) -> None:
    """Malformed state.json triggers WARN log but writer still succeeds."""
    bad_path = tmp_path / ".claude" / "state.json"
    bad_path.parent.mkdir(parents=True, exist_ok=True)
    bad_path.write_text("{this is not valid json", encoding="utf-8")

    writer = BriefingSnapshotWriter(project_root=tmp_path)
    with caplog.at_level(logging.WARNING, logger="src.scanner.automation.briefing_snapshot"):
        ok = writer.write_now(trigger="boot")

    assert ok is True
    snap_path = tmp_path / ".claude" / "brain" / "snapshot.md"
    assert snap_path.exists()
    # Verify a WARN-level message about the corrupt file was emitted
    warn_msgs = [r.message for r in caplog.records if r.levelno >= logging.WARNING]
    assert any("corrupt JSON" in m or "state.json" in m for m in warn_msgs), (
        f"expected WARN about corrupt state.json, got: {warn_msgs}"
    )


def test_diff_detection_skips_redundant_writes(tmp_path: Path) -> None:
    """Identical meaningful state on a 2nd write does NOT re-replace the file."""
    _seed_minimal_state(tmp_path)

    writer = BriefingSnapshotWriter(project_root=tmp_path)
    assert writer.write_now(trigger="boot") is True
    snap_path = tmp_path / ".claude" / "brain" / "snapshot.md"
    first_mtime = snap_path.stat().st_mtime

    # Sleep just enough that os.replace would change the mtime if it ran.
    time.sleep(0.05)
    assert writer.write_now(trigger="boot") is True

    second_mtime = snap_path.stat().st_mtime
    # The diff-and-write semantics should produce identical mtime — meaningful
    # state didn't change, the timestamps in `_DIFF_IGNORE_KEYS` are excluded
    # from the diff, and the trigger label itself is also ignored.
    assert second_mtime == first_mtime, (
        "diff detection should skip rewrite when meaningful state unchanged"
    )

    # Heartbeat should record the skip on the second call.
    hb = json.loads((tmp_path / ".claude" / "snapshot_heartbeat.json").read_text())
    assert hb.get("skipped") == "no_meaningful_change"


def test_boot_write_fires_with_no_cycle_data(tmp_path: Path) -> None:
    """Fresh tmp dir, write_now(trigger='boot') succeeds with placeholders."""
    writer = BriefingSnapshotWriter(project_root=tmp_path)
    assert writer.write_now(trigger="boot") is True

    snap = (tmp_path / ".claude" / "brain" / "snapshot.md").read_text()
    assert "last-write-trigger: `boot`" in snap
    # Heartbeat sidecar written
    hb = json.loads((tmp_path / ".claude" / "snapshot_heartbeat.json").read_text())
    assert hb["last_success_utc"] is not None
    assert hb["last_error"] is None


def test_atomic_rename_failure_logs_no_partial_file(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    caplog,
) -> None:
    """Simulated os.replace failure -> ERROR log, snapshot.md unchanged from
    previous content, heartbeat reflects the failure."""
    _seed_minimal_state(tmp_path)
    writer = BriefingSnapshotWriter(project_root=tmp_path)

    # First write succeeds normally — we need a baseline snapshot to assert
    # "unchanged from previous content" against.
    assert writer.write_now(trigger="first") is True
    snap_path = tmp_path / ".claude" / "brain" / "snapshot.md"
    baseline_content = snap_path.read_text()
    baseline_mtime = snap_path.stat().st_mtime

    # Mutate state so the diff detector WOULD trigger a rewrite, then break
    # os.replace via monkeypatch (this is environmental injection, NOT a mock
    # of code under test).
    _write_json(tmp_path / ".claude" / "state.json", {
        "halted": True,  # change so diff fires
        "mode": "demo",
        "scan_cycle_count": 99,
    })
    # Wrap os.replace so it ONLY fails on the snapshot.md target. The
    # heartbeat write also uses os.replace and must still succeed so we
    # can read it back to confirm the failure was recorded.
    real_replace = os.replace
    snap_path_str = str(snap_path)

    def selective_boom(src, dst, *args, **kwargs):  # noqa: ANN001
        if str(dst) == snap_path_str:
            raise OSError(28, "No space left on device")
        return real_replace(src, dst, *args, **kwargs)

    monkeypatch.setattr(
        "src.scanner.automation.briefing_snapshot.os.replace",
        selective_boom,
    )

    with caplog.at_level(logging.ERROR, logger="src.scanner.automation.briefing_snapshot"):
        ok = writer.write_now(trigger="should_fail")

    assert ok is False
    # snapshot.md must be unchanged (atomic semantics — no partial file)
    assert snap_path.read_text() == baseline_content
    assert snap_path.stat().st_mtime == baseline_mtime
    # ERROR log present
    err_msgs = [r.message for r in caplog.records if r.levelno >= logging.ERROR]
    assert any("write failed" in m for m in err_msgs), (
        f"expected ERROR about write failure, got: {err_msgs}"
    )
    # Heartbeat reflects the failure (heartbeat write itself succeeded
    # because selective_boom only fails on the snapshot target)
    hb = json.loads((tmp_path / ".claude" / "snapshot_heartbeat.json").read_text())
    assert hb["last_error"] is not None
    assert "No space left" in hb["last_error"] or "OSError" in hb["last_error"]


def test_halt_reason_extracted_from_alert_state(tmp_path: Path) -> None:
    """halted=True in state.json + an alert in alert_state.json -> snapshot
    surfaces the alert type as halt_reason."""
    _seed_minimal_state(tmp_path, halted=True)
    # Overwrite alerts with an active one
    _write_json(tmp_path / ".claude" / "alert_state.json", {
        "active_alerts": [
            {"type": "consecutive_losses", "value": 16, "threshold": 5}
        ],
        "last_fired": {"consecutive_losses": 1778332923.0},
        "last_updated": "2026-05-10T18:57:02",
    })

    writer = BriefingSnapshotWriter(project_root=tmp_path)
    assert writer.write_now(trigger="boot") is True

    snap = (tmp_path / ".claude" / "brain" / "snapshot.md").read_text()
    # Halt context renders the halted branch with the reason
    assert "HALTED" in snap
    assert "consecutive_losses" in snap
    # And the timestamp from safe_restart is rendered
    assert "2026-05-09" in snap


def test_briefing_md_is_never_written(tmp_path: Path) -> None:
    """Hard invariant: this writer must not create or modify briefing.md.

    We pre-create a briefing.md with sentinel content and verify it survives.
    """
    briefing = tmp_path / ".claude" / "brain" / "briefing.md"
    briefing.parent.mkdir(parents=True, exist_ok=True)
    sentinel = "# Operator-curated briefing — DO NOT TOUCH\n"
    briefing.write_text(sentinel, encoding="utf-8")
    briefing_mtime = briefing.stat().st_mtime

    _seed_minimal_state(tmp_path, halted=True)
    writer = BriefingSnapshotWriter(project_root=tmp_path)
    assert writer.write_now(trigger="boot") is True
    # Multiple writes for good measure
    assert writer.maybe_write(cycle_count=12, every_n=12) is True

    # briefing.md is byte-identical and untouched
    assert briefing.read_text() == sentinel
    assert briefing.stat().st_mtime == briefing_mtime
    # snapshot.md exists separately
    assert (tmp_path / ".claude" / "brain" / "snapshot.md").exists()


def test_maybe_write_cadence_skips_off_cycles(tmp_path: Path) -> None:
    """maybe_write only fires on cycles divisible by every_n."""
    _seed_minimal_state(tmp_path)
    writer = BriefingSnapshotWriter(project_root=tmp_path)

    # Off-cycle: should be False, no file
    assert writer.maybe_write(cycle_count=7, every_n=12) is False
    assert not (tmp_path / ".claude" / "brain" / "snapshot.md").exists()

    # On-cycle: writes
    assert writer.maybe_write(cycle_count=12, every_n=12) is True
    assert (tmp_path / ".claude" / "brain" / "snapshot.md").exists()

    # every_n <= 0 disables
    assert writer.maybe_write(cycle_count=12, every_n=0) is False


# ── Helpers (kept at file end so test reads top-down) ────────────────


def _now_iso() -> str:
    """Return an ISO timestamp guaranteed to fall inside the 24h window."""
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).isoformat()
