"""Tests for the synthetic Platt scaling prior generated by
``scripts/fit_platt_synthetic.py``.

NO MOCKS (CLAUDE.md / .claude/rules/improvement.md No-Mock Rule). Uses real
ConfidenceCalibrationSystem against real disk via pytest's tmp_path.

Three tests:
1. Empty params: _platt_scale returns the raw score with is_calibrated=False.
2. Synthetic params (coef=4, intercept=-2): _platt_scale maps 0.582 to a
   sensible value in (0.55, 0.7) — sigmoid is monotonic and 0.582 is
   mid-range.
3. Full calibrate() pipeline: synthetic Platt produces a DIFFERENT
   final_confidence vs the raw-passthrough no-cal case, in the direction the
   sigmoid prior dictates.

Note on Test 3 direction: synthetic Platt with coef=4.0, intercept=-2.0 has
inflection at raw=0.5 with slope 1 there. It REGRESSES extreme scores toward
0.5 — raw=0.7 -> ~0.69 (slightly lower), raw=0.3 -> ~0.31 (slightly higher).
The brief expected "higher final_confidence with synthetic Platt", which is
true for raw < 0.5 but the opposite for raw > 0.5. We test the case the
brief intended (raw < 0.5) plus an inversion check (raw > 0.5 produces a
LOWER final_confidence — proving the prior is conservative, which is what we
want for an untrained calibrator).
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import List

import pytest

# Ensure project root on path so `from src.scanner...` resolves when pytest
# is invoked from outside the package.
import sys
_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

from src.scanner.confidence_calibration import (
    CalibrationConfig,
    ConfidenceCalibrationSystem,
)


# Synthetic prior chosen by scripts/fit_platt_synthetic.py defaults.
SYNTHETIC_COEF = 4.0
SYNTHETIC_INTERCEPT = -2.0


def _write_calibration_file(path: Path, payload: dict) -> None:
    """Atomic JSON write — same shape ConfidenceCalibrationSystem._save uses."""
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    with open(tmp, "w") as f:
        json.dump(payload, f, indent=2, sort_keys=True)
        f.flush()
        os.fsync(f.fileno())
    os.rename(tmp, path)


def _build_synthetic_payload(coef: float, intercept: float) -> dict:
    return {
        "version": 1,
        "platt_params": {
            "_global": {"coef": coef, "intercept": intercept},
        },
        "trade_history": [],
        "metadata": {"source": "synthetic_prior"},
    }


def _verdicts(scores: List[float], weights: List[float]) -> List[dict]:
    """Build a list of dict-form verdicts — _verdict_val handles dicts natively.

    No mocks: just the dicts that ConfidenceCalibrationSystem accepts.
    """
    assert len(scores) == len(weights)
    out = []
    for i, (s, w) in enumerate(zip(scores, weights)):
        out.append({
            "name": f"agent_{i}",
            "score": float(s),
            "weight": float(w),
            "passed": s >= 0.5,
        })
    return out


# ---------------------------------------------------------------------------
# Test 1 — empty params: _platt_scale falls through to raw passthrough.
# ---------------------------------------------------------------------------
def test_empty_params_passes_through_raw(tmp_path: Path) -> None:
    cal_file = tmp_path / "calibration_params.json"
    # Real disk, real schema, but no platt_params.
    _write_calibration_file(cal_file, {"version": 1, "platt_params": {}})

    cfg = CalibrationConfig(calibration_file=str(cal_file))
    system = ConfidenceCalibrationSystem(config=cfg)

    # Sanity: the calibrator did NOT load any platt params.
    assert system._platt_params == {}, system._platt_params

    for raw in (0.10, 0.30, 0.50, 0.582, 0.70, 0.90):
        cal, is_cal = system._platt_scale(raw, "NORMAL")
        # Identity passthrough — raw returned exactly, is_calibrated=False.
        assert is_cal is False, f"raw={raw}: expected is_calibrated=False"
        assert abs(cal - raw) < 1e-9, f"raw={raw}: expected identity, got {cal}"


# ---------------------------------------------------------------------------
# Test 2 — synthetic params produce a sensible monotone mapping at 0.582.
# ---------------------------------------------------------------------------
def test_synthetic_params_map_058_to_sensible_value(tmp_path: Path) -> None:
    cal_file = tmp_path / "calibration_params.json"
    _write_calibration_file(
        cal_file,
        _build_synthetic_payload(SYNTHETIC_COEF, SYNTHETIC_INTERCEPT),
    )

    cfg = CalibrationConfig(calibration_file=str(cal_file))
    system = ConfidenceCalibrationSystem(config=cfg)

    assert "_global" in system._platt_params, system._platt_params
    assert system._platt_params["_global"]["coef"] == SYNTHETIC_COEF
    assert system._platt_params["_global"]["intercept"] == SYNTHETIC_INTERCEPT

    # NORMAL is not in platt_params -> falls through to "_global".
    cal, is_cal = system._platt_scale(0.582, "NORMAL")
    assert is_cal is True
    assert 0.55 < cal < 0.70, f"raw=0.582 -> {cal}, expected in (0.55, 0.70)"

    # Spot-check a few more points: monotone increasing, fixed point at 0.5.
    cal_at_05, _ = system._platt_scale(0.5, "NORMAL")
    assert abs(cal_at_05 - 0.5) < 1e-6, cal_at_05  # exact midpoint
    cal_at_03, _ = system._platt_scale(0.3, "NORMAL")
    cal_at_07, _ = system._platt_scale(0.7, "NORMAL")
    # Symmetric about 0.5: cal(0.3) + cal(0.7) ~ 1.0
    assert abs((cal_at_03 + cal_at_07) - 1.0) < 1e-6


# ---------------------------------------------------------------------------
# Test 3 — full calibrate() pipeline: synthetic Platt CHANGES final_confidence
# vs no-cal, in the direction the sigmoid dictates.
#
# coef=4, intercept=-2 has inflection at raw=0.5 with slope 1 there. It
# regresses extreme scores toward 0.5: raw < 0.5 -> calibrated > raw (HIGHER
# confidence), raw > 0.5 -> calibrated < raw (LOWER confidence). We assert
# both directions to prove the calibration path is wired AND directionally
# correct.
# ---------------------------------------------------------------------------
def test_calibrate_pipeline_uses_platt_when_present(tmp_path: Path) -> None:
    # Two real calibrators against real disk: one with synthetic Platt, one
    # with no params (raw passthrough).
    synth_file = tmp_path / "calibration_synth.json"
    _write_calibration_file(
        synth_file,
        _build_synthetic_payload(SYNTHETIC_COEF, SYNTHETIC_INTERCEPT),
    )
    empty_file = tmp_path / "calibration_empty.json"
    _write_calibration_file(empty_file, {"version": 1, "platt_params": {}})

    synth = ConfidenceCalibrationSystem(
        config=CalibrationConfig(calibration_file=str(synth_file))
    )
    bare = ConfidenceCalibrationSystem(
        config=CalibrationConfig(calibration_file=str(empty_file))
    )

    # Verdicts engineered so weighted score is just below 0.5 (low-confidence
    # case where synthetic Platt INFLATES toward 0.5).
    low_verdicts = _verdicts(
        scores=[0.40, 0.42, 0.44, 0.46, 0.42, 0.40, 0.44, 0.46],
        weights=[1.0] * 8,
    )
    res_synth_low = synth.calibrate(low_verdicts, regime_name="NORMAL")
    res_bare_low = bare.calibrate(low_verdicts, regime_name="NORMAL")

    # Calibration is "calibrated" only on the synth side.
    assert res_synth_low.is_calibrated is True
    assert res_bare_low.is_calibrated is False
    # platt_calibrated > raw_weighted_score on the synth side (mid<0.5 lifts).
    assert res_synth_low.platt_calibrated > res_synth_low.raw_weighted_score, (
        f"synth platt={res_synth_low.platt_calibrated}, "
        f"raw={res_synth_low.raw_weighted_score}"
    )
    # And final_confidence is HIGHER under synth Platt vs raw passthrough.
    assert res_synth_low.final_confidence > res_bare_low.final_confidence, (
        f"synth final={res_synth_low.final_confidence}, "
        f"bare final={res_bare_low.final_confidence}"
    )

    # Inversion: above-midpoint verdicts get LOWER final_confidence under
    # synth Platt (regression toward 0.5 is the conservative behavior we want
    # for an untrained calibrator). This proves the path is exercised, not
    # just that one direction happens to align.
    high_verdicts = _verdicts(
        scores=[0.70, 0.72, 0.68, 0.74, 0.70, 0.72, 0.68, 0.74],
        weights=[1.0] * 8,
    )
    res_synth_high = synth.calibrate(high_verdicts, regime_name="NORMAL")
    res_bare_high = bare.calibrate(high_verdicts, regime_name="NORMAL")

    assert res_synth_high.is_calibrated is True
    assert res_bare_high.is_calibrated is False
    assert res_synth_high.platt_calibrated < res_synth_high.raw_weighted_score, (
        f"synth platt={res_synth_high.platt_calibrated}, "
        f"raw={res_synth_high.raw_weighted_score}"
    )
    assert res_synth_high.final_confidence < res_bare_high.final_confidence, (
        f"synth final={res_synth_high.final_confidence}, "
        f"bare final={res_bare_high.final_confidence}"
    )
