"""Synthetic agent behavior generators for observational learning.

US-078: Generate synthetic trade scenarios from 5 rule-based agent types:
1. MomentumChaser — trades breakouts, high-confidence directional moves
2. MeanReversionScalper — fades extremes, buys oversold / sells overbought
3. RiskAverse — only trades high R:R setups in low-vol regimes
4. MacroCyclical — follows session timing and macro trends
5. NewsReactive — trades around news events with wide SL

These synthetic agents produce simulated trade sequences from historical
candle data. The resulting patterns are used by ObservationalLearner to
extract winning conditions and accelerate RL convergence.
"""

from __future__ import annotations

import logging
import math
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)

# Trade outcome types
OUTCOME_WIN = "WIN"
OUTCOME_LOSS = "LOSS"
OUTCOME_BREAKEVEN = "BREAKEVEN"
OUTCOME_TIMEOUT = "TIMEOUT"


@dataclass
class SyntheticTrade:
    """A single synthetic trade generated by a behavior agent."""

    agent_type: str = ""
    pair: str = ""
    direction: str = ""  # LONG or SHORT
    entry_bar: int = 0
    exit_bar: int = 0
    entry_price: float = 0.0
    exit_price: float = 0.0
    sl_pips: float = 0.0
    tp_pips: float = 0.0
    outcome: str = ""  # WIN, LOSS, BREAKEVEN, TIMEOUT
    pnl_pips: float = 0.0
    hold_bars: int = 0
    confidence: float = 0.0
    regime: str = "NORMAL"
    features: Dict[str, float] = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "agent_type": self.agent_type,
            "pair": self.pair,
            "direction": self.direction,
            "entry_bar": self.entry_bar,
            "exit_bar": self.exit_bar,
            "entry_price": round(self.entry_price, 6),
            "exit_price": round(self.exit_price, 6),
            "sl_pips": round(self.sl_pips, 2),
            "tp_pips": round(self.tp_pips, 2),
            "outcome": self.outcome,
            "pnl_pips": round(self.pnl_pips, 2),
            "hold_bars": self.hold_bars,
            "confidence": round(self.confidence, 4),
            "regime": self.regime,
            "features": {k: round(v, 6) for k, v in self.features.items()},
        }


class SyntheticAgent(ABC):
    """Base class for synthetic behavior agents."""

    agent_type: str = "base"

    @abstractmethod
    def generate_signals(
        self,
        df: pd.DataFrame,
        pair: str = "",
        pip_value: float = 0.0001,
    ) -> List[SyntheticTrade]:
        """Generate synthetic trades from historical candle data.

        Args:
            df: DataFrame with OHLCV columns
            pair: Instrument name
            pip_value: Pip value for the pair

        Returns:
            List of SyntheticTrade objects
        """
        ...

    @staticmethod
    def _compute_atr(df: pd.DataFrame, period: int = 14) -> pd.Series:
        """Compute ATR from OHLCV data."""
        high_low = df["high"] - df["low"]
        high_close = (df["high"] - df["close"].shift(1)).abs()
        low_close = (df["low"] - df["close"].shift(1)).abs()
        tr = pd.concat([high_low, high_close, low_close], axis=1).max(axis=1)
        return tr.rolling(period).mean()

    @staticmethod
    def _compute_rsi(df: pd.DataFrame, period: int = 14) -> pd.Series:
        """Compute RSI."""
        delta = df["close"].diff()
        gain = delta.clip(lower=0).rolling(period).mean()
        loss = (-delta.clip(upper=0)).rolling(period).mean()
        rs = gain / loss.replace(0, np.nan)
        return 100 - (100 / (1 + rs))

    def _simulate_trade_outcome(
        self,
        df: pd.DataFrame,
        entry_bar: int,
        direction: str,
        sl_pips: float,
        tp_pips: float,
        pip_value: float,
        max_hold: int = 50,
    ) -> SyntheticTrade:
        """Simulate forward from entry to determine outcome."""
        entry_price = float(df["close"].iloc[entry_bar])
        trade = SyntheticTrade(
            agent_type=self.agent_type,
            entry_bar=entry_bar,
            entry_price=entry_price,
            sl_pips=sl_pips,
            tp_pips=tp_pips,
            direction=direction,
        )

        sl_dist = sl_pips * pip_value
        tp_dist = tp_pips * pip_value

        for i in range(entry_bar + 1, min(entry_bar + max_hold, len(df))):
            price = float(df["close"].iloc[i])

            if direction == "LONG":
                pnl = (price - entry_price) / pip_value
                if price <= entry_price - sl_dist:
                    trade.outcome = OUTCOME_LOSS
                    trade.pnl_pips = -sl_pips
                    trade.exit_bar = i
                    trade.exit_price = entry_price - sl_dist
                    break
                elif price >= entry_price + tp_dist:
                    trade.outcome = OUTCOME_WIN
                    trade.pnl_pips = tp_pips
                    trade.exit_bar = i
                    trade.exit_price = entry_price + tp_dist
                    break
            else:  # SHORT
                pnl = (entry_price - price) / pip_value
                if price >= entry_price + sl_dist:
                    trade.outcome = OUTCOME_LOSS
                    trade.pnl_pips = -sl_pips
                    trade.exit_bar = i
                    trade.exit_price = entry_price + sl_dist
                    break
                elif price <= entry_price - tp_dist:
                    trade.outcome = OUTCOME_WIN
                    trade.pnl_pips = tp_pips
                    trade.exit_bar = i
                    trade.exit_price = entry_price - tp_dist
                    break
        else:
            # Timeout
            trade.outcome = OUTCOME_TIMEOUT
            trade.exit_bar = min(entry_bar + max_hold, len(df) - 1)
            trade.exit_price = float(df["close"].iloc[trade.exit_bar])
            if direction == "LONG":
                trade.pnl_pips = (trade.exit_price - entry_price) / pip_value
            else:
                trade.pnl_pips = (entry_price - trade.exit_price) / pip_value

        trade.hold_bars = trade.exit_bar - trade.entry_bar
        return trade


class MomentumChaser(SyntheticAgent):
    """Trades breakouts with trend following."""

    agent_type = "momentum_chaser"

    def generate_signals(self, df, pair="", pip_value=0.0001):
        trades = []
        if len(df) < 50:
            return trades

        atr = self._compute_atr(df)
        sma20 = df["close"].rolling(20).mean()
        sma50 = df["close"].rolling(50).mean()

        for i in range(51, len(df) - 50):
            if pd.isna(atr.iloc[i]) or atr.iloc[i] <= 0:
                continue
            atr_pips = atr.iloc[i] / pip_value

            # Long: price > SMA20 > SMA50 and close > prev high
            if (df["close"].iloc[i] > sma20.iloc[i] > sma50.iloc[i]
                    and df["close"].iloc[i] > df["high"].iloc[i - 1]):
                trade = self._simulate_trade_outcome(
                    df, i, "LONG", sl_pips=atr_pips * 1.5, tp_pips=atr_pips * 3.0,
                    pip_value=pip_value,
                )
                trade.pair = pair
                trade.confidence = 0.65
                trade.features = {
                    "sma_spread": float(sma20.iloc[i] - sma50.iloc[i]),
                    "atr_pips": float(atr_pips),
                }
                trades.append(trade)

            # Short: price < SMA20 < SMA50 and close < prev low
            elif (df["close"].iloc[i] < sma20.iloc[i] < sma50.iloc[i]
                  and df["close"].iloc[i] < df["low"].iloc[i - 1]):
                trade = self._simulate_trade_outcome(
                    df, i, "SHORT", sl_pips=atr_pips * 1.5, tp_pips=atr_pips * 3.0,
                    pip_value=pip_value,
                )
                trade.pair = pair
                trade.confidence = 0.65
                trade.features = {
                    "sma_spread": float(sma20.iloc[i] - sma50.iloc[i]),
                    "atr_pips": float(atr_pips),
                }
                trades.append(trade)

        return trades


class MeanReversionScalper(SyntheticAgent):
    """Fades extremes using RSI."""

    agent_type = "mean_reversion_scalper"

    def generate_signals(self, df, pair="", pip_value=0.0001):
        trades = []
        if len(df) < 30:
            return trades

        atr = self._compute_atr(df)
        rsi = self._compute_rsi(df)

        for i in range(20, len(df) - 50):
            if pd.isna(atr.iloc[i]) or pd.isna(rsi.iloc[i]) or atr.iloc[i] <= 0:
                continue
            atr_pips = atr.iloc[i] / pip_value

            # Long on oversold RSI < 25
            if rsi.iloc[i] < 25:
                trade = self._simulate_trade_outcome(
                    df, i, "LONG", sl_pips=atr_pips * 1.0, tp_pips=atr_pips * 1.5,
                    pip_value=pip_value, max_hold=20,
                )
                trade.pair = pair
                trade.confidence = 0.55
                trade.features = {"rsi": float(rsi.iloc[i]), "atr_pips": float(atr_pips)}
                trades.append(trade)

            # Short on overbought RSI > 75
            elif rsi.iloc[i] > 75:
                trade = self._simulate_trade_outcome(
                    df, i, "SHORT", sl_pips=atr_pips * 1.0, tp_pips=atr_pips * 1.5,
                    pip_value=pip_value, max_hold=20,
                )
                trade.pair = pair
                trade.confidence = 0.55
                trade.features = {"rsi": float(rsi.iloc[i]), "atr_pips": float(atr_pips)}
                trades.append(trade)

        return trades


class RiskAverseAgent(SyntheticAgent):
    """Only takes high R:R setups with strong confirmation."""

    agent_type = "risk_averse"

    def generate_signals(self, df, pair="", pip_value=0.0001):
        trades = []
        if len(df) < 50:
            return trades

        atr = self._compute_atr(df)
        sma20 = df["close"].rolling(20).mean()
        volatility = df["close"].pct_change().rolling(20).std()

        for i in range(50, len(df) - 50):
            if pd.isna(atr.iloc[i]) or pd.isna(volatility.iloc[i]) or atr.iloc[i] <= 0:
                continue
            atr_pips = atr.iloc[i] / pip_value

            # Only trade in low volatility (< 25th percentile)
            vol_pctile = volatility.iloc[:i].rank(pct=True).iloc[-1] if i > 20 else 0.5
            if vol_pctile > 0.25:
                continue

            # High R:R: tight SL, wide TP
            if df["close"].iloc[i] > sma20.iloc[i] and df["close"].iloc[i - 1] <= sma20.iloc[i - 1]:
                trade = self._simulate_trade_outcome(
                    df, i, "LONG", sl_pips=atr_pips * 0.8, tp_pips=atr_pips * 3.0,
                    pip_value=pip_value,
                )
                trade.pair = pair
                trade.confidence = 0.75
                trade.regime = "LOW"
                trade.features = {
                    "vol_percentile": float(vol_pctile),
                    "atr_pips": float(atr_pips),
                    "rr_ratio": 3.75,
                }
                trades.append(trade)

        return trades


class MacroCyclicalAgent(SyntheticAgent):
    """Follows weekly/session patterns."""

    agent_type = "macro_cyclical"

    def generate_signals(self, df, pair="", pip_value=0.0001):
        trades = []
        if len(df) < 100:
            return trades

        atr = self._compute_atr(df)
        sma50 = df["close"].rolling(50).mean()

        for i in range(50, len(df) - 50, 5):  # Check every 5 bars (session intervals)
            if pd.isna(atr.iloc[i]) or atr.iloc[i] <= 0:
                continue
            atr_pips = atr.iloc[i] / pip_value

            # Trend direction from longer-term SMA
            trend = "LONG" if df["close"].iloc[i] > sma50.iloc[i] else "SHORT"

            # Only trade if confirmed by last 5-bar momentum
            momentum = (df["close"].iloc[i] - df["close"].iloc[i - 5]) / pip_value
            if (trend == "LONG" and momentum > atr_pips * 0.5) or \
               (trend == "SHORT" and momentum < -atr_pips * 0.5):
                trade = self._simulate_trade_outcome(
                    df, i, trend, sl_pips=atr_pips * 2.0, tp_pips=atr_pips * 2.5,
                    pip_value=pip_value, max_hold=30,
                )
                trade.pair = pair
                trade.confidence = 0.60
                trade.features = {
                    "momentum_pips": float(momentum),
                    "atr_pips": float(atr_pips),
                }
                trades.append(trade)

        return trades


class NewsReactiveAgent(SyntheticAgent):
    """Trades volatility spikes (proxy for news events)."""

    agent_type = "news_reactive"

    def generate_signals(self, df, pair="", pip_value=0.0001):
        trades = []
        if len(df) < 30:
            return trades

        atr = self._compute_atr(df)
        # Detect volatility spikes: bar range > 2x ATR
        bar_range = (df["high"] - df["low"]) / pip_value

        for i in range(20, len(df) - 50):
            if pd.isna(atr.iloc[i]) or atr.iloc[i] <= 0:
                continue
            atr_pips = atr.iloc[i] / pip_value

            # Spike: this bar's range > 2x average
            if bar_range.iloc[i] > atr_pips * 2.0:
                # Trade in direction of the spike bar
                direction = "LONG" if df["close"].iloc[i] > df["open"].iloc[i] else "SHORT"
                trade = self._simulate_trade_outcome(
                    df, i, direction, sl_pips=atr_pips * 2.5, tp_pips=atr_pips * 2.0,
                    pip_value=pip_value, max_hold=15,
                )
                trade.pair = pair
                trade.confidence = 0.50
                trade.regime = "HIGH"
                trade.features = {
                    "spike_ratio": float(bar_range.iloc[i] / atr_pips),
                    "atr_pips": float(atr_pips),
                }
                trades.append(trade)

        return trades


# Registry of all synthetic agent types
SYNTHETIC_AGENTS: Dict[str, type] = {
    "momentum_chaser": MomentumChaser,
    "mean_reversion_scalper": MeanReversionScalper,
    "risk_averse": RiskAverseAgent,
    "macro_cyclical": MacroCyclicalAgent,
    "news_reactive": NewsReactiveAgent,
}


def simulate_all_agents(
    df: pd.DataFrame,
    pair: str = "",
    pip_value: float = 0.0001,
) -> List[SyntheticTrade]:
    """Run all 5 synthetic agents on the given data.

    Args:
        df: Historical OHLCV DataFrame
        pair: Instrument name
        pip_value: Pip value for the pair

    Returns:
        Combined list of all synthetic trades
    """
    all_trades: List[SyntheticTrade] = []
    for name, agent_class in SYNTHETIC_AGENTS.items():
        try:
            agent = agent_class()
            trades = agent.generate_signals(df, pair, pip_value)
            all_trades.extend(trades)
            logger.debug(
                "Synthetic agent %s generated %d trades for %s",
                name, len(trades), pair,
            )
        except Exception as e:
            logger.debug(f"Synthetic agent {name} failed: {e}")

    return all_trades
