"""Forward-ledger engine — evidence-safe recording for strategy shadow lanes.

2026-07-19 review of f590485 found the first lane recorders were NOT
evidence-safe, three ways:

1. **The first row was not genuinely forward.** Both lanes computed the full
   historical series, took its latest bar, and recorded that bar's
   already-realized return as "forward cycle 1" — a return known (possibly
   weeks old, given dump lag) at activation time. A legitimate first run
   establishes a BASELINE: book snapshot, realized return null, cumulative 0.
   Returns count only for bars STRICTLY LATER than the activation snapshot.
2. **Missed scheduler days were silently lost.** Recording only the latest
   bar means a 3-day scheduler gap drops those bars forever, corrupting
   cumulative return and Sharpe. The engine appends EVERY unseen bar
   strictly after the ledger's last asof, chronologically — deterministic
   backfill of a FROZEN specification, not backtest contamination: each bar
   is appended exactly once, from the same frozen rule, whenever it first
   becomes available.
3. **The logged book was not period-aligned.** The frozen constructions are
   causal (``shift(1)``): the return realized at ``t`` was generated by the
   book decided at ``t-1``. One "book" field conflated the book that EARNED
   the row's return with the CURRENT standing target. Rows now carry both:
   ``applied_book`` (decided at ``decision_asof`` = period start; generated
   ``today_net_return`` over ``return_period_start -> return_period_end``)
   and ``book`` (the standing next-bar target as of the row's asof — what
   the hedge registry should load).

Row kinds:
  * ``kind="activation"`` — baseline snapshot. ``today_net_return`` null,
    ``applied_book`` null, ``cumulative_shadow_return`` 0.0. Never counted
    as a forward observation.
  * ``kind="forward"`` — one genuinely-unseen bar. Cumulative compounds
    forward rows only.

Append-only JSONL, flush+fsync, duplicate-safe by construction (only bars
strictly after the last recorded asof are ever appended — re-running on
stale data is a no-op).
"""
from __future__ import annotations

import json
import logging
import os
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

logger = logging.getLogger(__name__)


def read_rows(path: Path) -> List[Dict[str, Any]]:
    """Tolerant JSONL reader (missing/corrupt-line-safe, never raises)."""
    if not path.exists():
        return []
    rows: List[Dict[str, Any]] = []
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        logger.warning("forward ledger unreadable at %s: %s", path, exc)
        return []
    for line in text.splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            rows.append(json.loads(line))
        except json.JSONDecodeError:
            logger.warning("skipping corrupt forward-ledger line in %s", path)
    return rows


def _append(path: Path, row: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    line = json.dumps(row, sort_keys=True) + "\n"
    with open(path, "a", encoding="utf-8") as fh:
        fh.write(line)
        fh.flush()
        os.fsync(fh.fileno())


def append_unseen_bars(
    ledger_path: Path,
    *,
    dates: List[str],
    payload_for: Callable[[str], Dict[str, Any]],
    activation_payload_for: Callable[[str], Dict[str, Any]],
    cycle_ts_iso: str,
) -> List[Dict[str, Any]]:
    """Advance a lane's forward ledger to the latest available bar.

    ``dates``: the frozen construction's FULL available bar dates, ascending
    (ISO strings). ``payload_for(d)`` returns the forward-row body for bar
    ``d`` — must include ``today_net_return`` (float, the realized return of
    bar ``d``), ``applied_book``, ``book`` (next-bar standing target),
    ``return_period_start``. ``activation_payload_for(d)`` returns the
    baseline body for the activation snapshot at the latest bar (book +
    metadata only; the engine forces the null-return baseline fields).

    Empty ledger  -> ONE activation row at the latest bar; NO return recorded
                     (that bar's return was already known at activation).
    Else          -> one forward row per bar strictly after the last recorded
                     asof, chronological, cumulative compounded over forward
                     rows only. Stale data -> [] (honest no-op).
    """
    if not dates:
        return []
    if sorted(dates) != list(dates):
        raise ValueError("forward_ledger: dates must be ascending — refusing unordered append")

    rows = read_rows(ledger_path)
    appended: List[Dict[str, Any]] = []

    if not rows:
        latest = dates[-1]
        row = dict(activation_payload_for(latest))
        row.update({
            "kind": "activation",
            "cycle_ts": cycle_ts_iso,
            "asof_date": latest,
            "today_net_return": None,
            "applied_book": None,
            "return_period_start": None,
            "return_period_end": None,
            "decision_asof": latest,
            "cumulative_shadow_return": 0.0,
            "forward_cycle_seq": 0,
            "orders_placed": 0,
            "broker": None,
        })
        _append(ledger_path, row)
        logger.info("forward ledger activated at %s (baseline, no realized return): %s",
                    latest, ledger_path)
        return [row]

    last_asof = str(rows[-1].get("asof_date", ""))
    prior_cum = _last_cumulative(rows)
    prior_seq = _last_forward_seq(rows)
    unseen = [d for d in dates if d > last_asof]
    if not unseen:
        logger.info("forward ledger: no bar after %s — honest no-op (%s)", last_asof, ledger_path)
        return []

    for d in unseen:
        body = dict(payload_for(d))
        net = body.get("today_net_return")
        if not isinstance(net, (int, float)):
            raise ValueError(f"forward_ledger: payload for {d} lacks a numeric today_net_return")
        prior_cum = (1.0 + prior_cum) * (1.0 + float(net)) - 1.0
        prior_seq += 1
        body.update({
            "kind": "forward",
            "cycle_ts": cycle_ts_iso,
            "asof_date": d,
            "return_period_end": d,
            "decision_asof": body.get("return_period_start"),
            "cumulative_shadow_return": prior_cum,
            "forward_cycle_seq": prior_seq,
            "orders_placed": 0,
            "broker": None,
        })
        _append(ledger_path, body)
        appended.append(body)
    return appended


def _last_cumulative(rows: List[Dict[str, Any]]) -> float:
    for r in reversed(rows):
        v = r.get("cumulative_shadow_return")
        if isinstance(v, (int, float)):
            return float(v)
    return 0.0


def _last_forward_seq(rows: List[Dict[str, Any]]) -> int:
    seqs = [int(r["forward_cycle_seq"]) for r in rows
            if isinstance(r.get("forward_cycle_seq"), (int, float))]
    return max(seqs) if seqs else 0


def forward_rows(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Only genuinely-forward observations (activation baselines excluded).
    Legacy rows without ``kind`` are treated as forward for backward compat
    with pre-engine ledgers — their provenance caveat is the ledger's own."""
    return [r for r in rows if r.get("kind", "forward") == "forward"
            and isinstance(r.get("today_net_return"), (int, float))]


def cadence_counts(rows: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Evidence-cadence accounting (review: 52 daily bars are NOT 52 weekly
    observations). Counts raw return bars, distinct ISO calendar weeks,
    distinct months, and completed rebalances (forward rows whose standing
    target book differs from the previous row's — actual holding-period
    boundaries, the honest denominator for weekly/monthly requirements)."""
    fwd = forward_rows(rows)
    weeks, months = set(), set()
    rebalances = 0
    prev_book: Optional[Dict[str, Any]] = None
    for r in rows:  # book changes tracked across activation too
        d = str(r.get("asof_date") or "")
        if r in fwd and len(d) >= 10:
            try:
                import datetime as _dt
                iso = _dt.date.fromisoformat(d[:10]).isocalendar()
                weeks.add((iso[0], iso[1]))
                months.add(d[:7])
            except ValueError:
                pass
        book = r.get("book")
        if isinstance(book, dict):
            flat = book.get("longs") if "longs" in book else book
            if prev_book is not None and flat != prev_book and r.get("kind", "forward") == "forward":
                rebalances += 1
            prev_book = flat
    return {
        "n_return_bars": len(fwd),
        "n_calendar_weeks": len(weeks),
        "n_calendar_months": len(months),
        "n_completed_rebalances": rebalances,
        "n_independent_holding_periods": rebalances,
        "note": ("weekly/monthly evidence requirements count rebalances/weeks, "
                 "NEVER raw daily bars"),
    }


__all__ = ["append_unseen_bars", "cadence_counts", "forward_rows", "read_rows"]
